### PR TITLE
Read props from stdin

### PR DESCRIPTION
**Pull request by joshwnj**
Sets props on the component from a json object in stdin, so you can do `cat example/props.json | reactview example/example.jsx`

### CODE REVIEW

**Comment by joshwnj** [comment]
PS. thanks for making this great project! I was tinkering with a very similar idea but didn't get it onto github yet :)

**Comment by zackify** [comment]
This looks great! I'm going to go over it in the morning and merge!

**Comment by zackify** [comment]
So after looking it over more I definitely like the approach, I'd also like to have an argument like: --props {test: 'it works'} what do you think? I'll still merge this in the morning though.  Edit: I've been up for too long. Obviously you can't have spaces there :P

**Comment by joshwnj** [comment]
cheers! nice idea on `--props`. I guess we'd have `--props` override `stdin` in the case where both are present?

**Comment by zackify** [comment]
yes I think you would have to be stupid to pipe into it AND do --props tho :p

**Comment by joshwnj** [comment]
btw I mentioned earlier I had been trying out a similar idea. finally got it onto github :) https://github.com/joshwnj/react-up

main differences:
- using browserify instead of webpack (i'm more familiar with that)
- sets up a websocket connection so that your stdin stream can send multiple prop updates
- no css support yet

Feel free to port over anything of interest from there.

**Comment by zackify** [comment]
Yeah I need the websocket setup

**Pull request merged**
